[package]
name = "deno_plguin_starter"
version = "0.1.0"
authors = ["迷渡 <justjavac@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.53.0"
futures = "0.3.5"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"